import { Filter } from 'lucide-react';
import { Download } from 'lucide-react';
import RevenueChart from '../../components/dashboard/RevenueChart';
import CategoryChart from '../../components/dashboard/CategoryChart';
import { FileText } from 'lucide-react';


const Reports = () => {
  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-3xl font-bold text-slate-900 dark:text-white tracking-tight">Reports & Analytics</h2>
          <p className="text-slate-500 dark:text-slate-400 mt-1">View detailed insights about your business performance.</p>
        </div>
        
        <div className="flex gap-3">
          <button className="flex items-center gap-2 px-4 py-2.5 glass-panel border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-all duration-300">
            <Filter className="w-4 h-4" />
            Filter
          </button>
          <button className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-primary to-primary-dark text-white rounded-xl hover:shadow-lg hover:shadow-primary/30 transition-all duration-300 text-sm font-semibold">
            <Download className="w-4 h-4" />
            Export Data
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="glass-panel p-6 rounded-2xl shadow-sm min-h-[400px]">
          <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-6 tracking-wide">Revenue Overview</h3>
          <RevenueChart />
        </div>
        <div className="glass-panel p-6 rounded-2xl shadow-sm min-h-[400px]">
          <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-6 tracking-wide">Services Distribution</h3>
          <CategoryChart />
        </div>
      </div>

      <div className="glass-panel rounded-2xl shadow-sm overflow-hidden p-0">
        <div className="p-6 border-b border-slate-200 dark:border-slate-700/50 bg-white/50 dark:bg-slate-900/50">
          <h3 className="text-lg font-bold text-slate-900 dark:text-white">Recent Generated Reports</h3>
        </div>
        <div className="premium-table-container rounded-none border-x-0 border-b-0 shadow-none">
          <table className="premium-table">
            <thead>
              <tr>
                <th className="premium-th">Report Name</th>
                <th className="premium-th">Date Range</th>
                <th className="premium-th">Generated By</th>
                <th className="premium-th text-right">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr className="premium-tr">
                <td className="premium-td flex items-center gap-3 font-semibold text-slate-900 dark:text-white">
                  <div className="p-2 bg-primary/10 rounded-lg text-primary"><FileText className="w-5 h-5" /></div>
                  Monthly Financial Summary
                </td>
                <td className="premium-td">June 2026</td>
                <td className="premium-td font-medium">Admin User</td>
                <td className="premium-td text-right"><button className="text-primary hover:text-primary-dark font-semibold transition-colors">Download PDF</button></td>
              </tr>
              <tr className="premium-tr">
                <td className="premium-td flex items-center gap-3 font-semibold text-slate-900 dark:text-white">
                  <div className="p-2 bg-blue-500/10 rounded-lg text-blue-500"><FileText className="w-5 h-5" /></div>
                  Inventory Usage Report
                </td>
                <td className="premium-td">Q2 2026</td>
                <td className="premium-td font-medium">System Auto</td>
                <td className="premium-td text-right"><button className="text-primary hover:text-primary-dark font-semibold transition-colors">Download PDF</button></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Reports;
